# Site settings
title: Quinn Greiner
email: quinndgreiner@yahoo.com
url: https://github.com/QuinnDGreiner
description: " Hello, and welcome to my portfolio website! My name is Quinn Greiner, and I am a fourth-year cybersecurity student at Grand Canyon University with a strong passion for technology and information security. Feel free to explore, and don’t hesitate to reach out if you have questions, want to collaborate on a project, or expand our professional networks within the cybersecurity community."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Quinns Portfolio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: LinkedIn
    url: https://www.linkedin.com/in/quinn-greiner/
  - title: github
    url: https://github.com/QuinnDGreiner

# Build settings
markdown: kramdown
permalink: pretty
